set current_schema= dw_kingmed;
drop table if exists dw_kingmed.LB_APPLICATION;
create table dw_kingmed.LB_APPLICATION
(
  application_id           CHAR(36) not null,
  application_source_id    CHAR(36),
  bc_upload_id             CHAR(36),
  return_app_id            CHAR(36),
  barcode                  VARCHAR2(30),
  checked_by               CHAR(36),
  check_date               DATE,
  app_status               CHAR(1) default 0 not null,
  customer_id              CHAR(36),
  priority                 CHAR(1) default 0 not null,
  is_personal_invoice      CHAR(1) default 0 not null,
  customization            VARCHAR2(240),
  application_type_code    VARCHAR2(30),
  box_number               VARCHAR2(30),
  is_health_checkup        CHAR(1) default 0 not null,
  is_input_error           CHAR(1) default 0 not null,
  is_urgent                CHAR(1) default 0 not null,
  is_office_accept         CHAR(1) default 0 not null,
  is_batch                 CHAR(1) default 0 not null,
  scheme_id                CHAR(36),
  kmct_proj_code           VARCHAR2(30),
  updp                     VARCHAR2(30),
  updn                     VARCHAR2(30),
  send_date                DATE,
  receipt_flag             VARCHAR2(30),
  remark                   VARCHAR2(240),
  return_remark            VARCHAR2(240),
  lot_id                   VARCHAR2(100),
  batch_flag_id            CHAR(36),
  collection_location_name VARCHAR2(500),
  collection_location      VARCHAR2(100),
  customer_name            VARCHAR2(300),
  line_name                VARCHAR2(100),
  archive_base_date        DATE default to_date('2099-12-31','yyyy-mm-dd') not null,
  biz_org_code             VARCHAR2(100) not null,
  created_by               CHAR(36) not null,
  creation_date            DATE not null,
  last_updated_by          CHAR(36) not null,
  last_update_date         DATE not null,
  record_version           NUMBER not null,
  deleted_flag             CHAR(1) default 0 not null,
  deleted_by               CHAR(36),
  deletion_date            DATE,
  bc_upload_type           VARCHAR2(100),
  kmct_proj_type           VARCHAR2(100),
  inocunote_type           VARCHAR2(30),
  send_bl_date             VARCHAR2(30),
  way                      VARCHAR2(2000),
  organization_code        VARCHAR2(100),
  organization_name        VARCHAR2(100),
  photo_type               CHAR(1) default 0 not null,
  upload_customer_id       CHAR(36),
  total_app_id             CHAR(36),
  collection_location_id   CHAR(36),
  organization_id          CHAR(36),
  patient_id               CHAR(36),
  pl_user_id               CHAR(36)
  
)
with (orientation = column, COMPRESSION=MIDDLE)
distribute by hash(APPLICATION_ID);